import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Nav from '../../components/nav'
import { useEffect, useState } from 'react'
import { auth } from '../../firebase/config'
import Router from 'next/router'
import { onAuthStateChanged } from 'firebase/auth'

export default function Cart() {
  const [cart, setCart] = useState([])
  useEffect(() => {
   
    console.log("auth", auth.currentUser?.uid)
    console.log("current user", auth.currentUser?.email)
    
    
    
  }, [])

  return (
    <div>
      <Nav />
      <Head>
        <title>KeyBoard Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Cart</h1>
    
      
    </div>
  )
}
