import Head from 'next/head'
import  { useRouter } from 'next/router'
import { getOneProduct } from "../../firebase/customerActions"
import { useEffect, useState } from 'react'


export default function Home() {
  const [productName, setProductName] = useState("")
  const [productImage, setProductImage] = useState("")
  const [productPrice, setProductPrice] = useState(0)
  const [reviews, setReviews] = useState<any[]>([])
  const [rating, setRating] = useState(0.0)

  const router = useRouter()
  const productUid = router.query.productId

  useEffect(() => {
    getOneProduct(productUid).then((res) => {
      console.log(res)
      setProductName(res?.productName)
      setProductImage(res?.productImage)
      setProductPrice(res?.productPrice)
      setReviews(res?.reviews)
      
    })
  }, [])

  return (

    <div>
      <Head>
        <title>KeyBoard Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Product</h1>
      <h1>{productName}</h1>
      <h1>{productPrice}</h1>
      <img src = {productImage}></img>
      {reviews.length === 0 ? "No reviews" : "Reviews"}
    
      
    </div>
    
  )
}
