import Head from 'next/head'
import  { useRouter } from 'next/router'
import { getOneProduct, addToCart } from "../../firebase/customerActions"
import { useEffect, useState } from 'react'
import { logout } from '../../firebase/auth'
import { auth } from '../../firebase/config'
import Link from 'next/link'
import Nav from '../../components/nav'
import { onAuthStateChanged } from 'firebase/auth'


export default function Home() {
  const [productName, setProductName] = useState("")
  const [productImage, setProductImage] = useState("")
  const [productPrice, setProductPrice] = useState(0)
  const [reviews, setReviews] = useState<any[]>([])
  const [product, setProduct] = useState({})
  const [rating, setRating] = useState(0.0)
  const [userID, setUserID] = useState("")


  const router = useRouter()
  



  useEffect(() => {
    let productUid;
    

    if(router.isReady){
      const { productId } = router.query
      productUid = productId
      getOneProduct(productUid).then((res) => {
       console.log(res)
        setProductName(res?.productName)
        setProductImage(res?.productImage)
        setProductPrice(res?.productPrice)
        setReviews(res?.reviews)
        setRating(res?.rating)
        setProduct(res)
        
      })
    }
  }, [])

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if(user){
        setUserID(user.uid)
      }
      else{
        console.log("No user")
      }
    })

  }, [])


  console.log("product", product)
  return (
    <div>
      <Head>
        <title>KeyBoard Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Nav />
      <div className = "flex flex-col gap-[9] lg:flex-row mt-[100px] place-items-center">
        <div className = "text-center  lg:place-items-center">
          <img className = "lg:ml-[100px]" src = {productImage}></img>
        </div>
        <div className = "flex flex-col gap-12 text-center lg:ml-[25%]">
          <div className = "">
            <h1 className = "text-5xl lg:text-7xl mb-5">{productName}</h1>
            <h1 className = "text-3xl lg:text-5xl">${productPrice}</h1>
          </div> 
          <div className = "flex flex-col place-items-center">
            <button onClick={() => {addToCart(userID, product)}} className = "bg-black text-white w-[70%] h-[50px] sm:w-[100%] sm:h-[70px] lg:w-[482px] lg:h-[81px] rounded-lg mb-[3%]">Add To Cart</button>
            <button className = "bg-green-500 text-white w-[70%] h-[50px] sm:w-[100%] sm:h-[70px] lg:w-[482px] lg:h-[81px] rounded-lg mb-[10%]">Buy Now</button>
            {rating}
            {reviews.length === 0 ? "No reviews" : "Reviews"}
          </div>
        </div>    
      </div>
    </div>
    
  )
}


export async function getServerSideProps(context: any){
  console.log(context.params)
  return {props: {"hello": "world"}}
}
