import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { auth } from '../../firebase/config'
import Router from 'next/router'
import Nav from '../../components/nav'
import { onAuthStateChanged } from 'firebase/auth'
import { getCart, getOneProduct } from '../../firebase/customerActions'

export default function Home() {
  const [cart, setCart] = useState<any[]>([])




  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if(user){
           getCart(user.uid).then((res) => {
            console.log(res)
            setCart(res)
          })
      }
      else{
        Router.push("/auth/login")
      }
    })
  }, [])







  return (
    <div>
      
      <Head>
        <title>KeyBoard Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
     <div className = "mt-20 flex flex-col lg:gap-[25%] lg:flex-row">
      {/*Checkout Products*/}
      <div className = "ml-48">
        <h1 className = "text-5xl">Checkout</h1>
        <div className = "flex flex-row gap-x-56">
          <p>Product</p>
          <p>Quantity</p>
          <p>Total Price</p>
          {cart.map((item) => {
            return(
              <>
              {item.productName}
              </>
              
            )
          })}
        </div>
        <div>

        </div>
        
        <button>Continue Shopping</button>
      </div>
      {/*Checkout Information*/}
      <div className = "">
        <h1 className = "text-5xl">Payment Info</h1>
      </div>
     </div>
      
    
      
    </div>
  )
}


