import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { useState, useEffect } from 'react'


export default function Home() {
  
  return (
    <div className="main">
      <Head>
        <title>KeyBoard Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className = "nav">
        <div className = "navTitle">
          The Keyboard Shop
        </div>
        <div className = "navOptions">
          <p>Cart</p>
          <p>Profile</p>
          <p>Menu</p>
        </div>
      </div>
    {/*Picture and Selling point*/}
      <div className = "welcome">
        <div>
          <h1>Find All Your Keyboard needs here</h1>
          <div className = "welcomeButton">
          <button >Shop now</button>
          </div>
          
        </div>
        
        <div className="welcomeImg">
          <img
          
          alt="Green Keyboard" 
          src = "https://firebasestorage.googleapis.com/v0/b/ecommerceproject-416fd.appspot.com/o/My%20project-2.png?alt=media&token=f40dd23a-ff06-4dc9-9caa-8a218040f16a"
          
        />
        </div>
        
      </div>
    
      
    </div>
  )
}
